=== biyaa29/xml/index3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="employees">
  <xs:complexType>
    <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="id" type="xs:integer"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="depart" type="xs:string"/>
                    <xs:element name="courses" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="course1" type="xs:string"/>
                                <xs:element name="course2" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== biyaa29/xml/index3.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index3.xsd">
    <employee>
        <id>244</id>
        <name>asad</name>
        <depart>software sales</depart>
        <courses>
            <course1>information technology</course1>
            <course2>software engineering</course2>
        </courses>
    </employee>
    <employee>
        <id>345</id>
        <name>azlaan</name>
        <depart>acadmices</depart>
        <courses>
            <course1>information technology</course1>
            <course2>software engineering</course2>
        </courses>
    </employee>
    <employee>
        <id>256</id>
        <name>mansab</name>
        <depart>accounts</depart>
        <courses>
            <course1>information technology</course1>
            <course2>software engineering</course2>
        </courses>
    </employee>
    <employee>
        <id>567</id>
        <name>rohaan</name>
        <depart>sales</depart>
        <courses>
            <course1>information technology</course1>
            <course2>software engineering</course2>
        </courses>
    </employee>
</employees>
